--- #BlackList Module
- hosts: all
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Adding Dummy modules to modprobe
    kernel_blacklist: name=dummy state=present
