--- #DELETAGE_TO Playbook
- hosts: stage
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installtelnet client
    yum: pkg=telnet state=installed
    delegate_to: 127.0.0.1

