--- #stopping a instance
- hosts: stage
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: stopping a ec2 instance
    ec2:
     region: us-west-2
     instance_ids: i-07317dedccc6c137c
     state: stopped
