--- #Packages include
- hosts: RedHat
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - include: packages/packages.yml
  - name: verify packages
    raw: yum list installed | httpd
    register: pack
  - debug: var=pack
