--- #LOCAL_ACTION Playbook
- hosts: RedHat
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing using local action
    local_action: command ping -c 5 namico6.mylabserver.com
    
  - name: Install ttelnet
    action: yum pkg=telnet state=installed
