--- #LOOPS EXAMPLE Playbook
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: creating users
    user: name={{ item }} state=present
    with_items:
    - user1
    - user2
    - user3
